// Action constants for activity logging
module.exports = {
  // action types
  types: {
    STATE_TRANSITION: 'ACTION_TYPE/STATE_TRANSITION',
    METADATA: 'ACTION_TYPE/METADATA',
    PROGRESS: 'ACTION_TYPE/PROGRESS',
  },
  // actions for state transition type
  REJECT: 'STATE_TRANSITION/REJECT',
  UNVERIFY: 'STATE_TRANSITION/UNVERIFY',
  VERIFY: 'STATE_TRANSITION/VERIFY',
  ASSIGN: 'STATE_TRANSITION/ASSIGN',
  DENY: 'STATE_TRANSITION/DENY',
  PROCESS: 'STATE_TRANSITION/PROCESS',
  RESOLVE: 'STATE_TRANSITION/RESOLVE',
  // actions for metadata type
  CREATE_PIN: 'METADATA/CREATE_PIN',
  UPDATE_PIN: 'METADATA/UPDATE_PIN',
  DELETE_PIN: 'METADATA/DELETE_PIN',
  // actions for progress type
  CREATE_PROGRESS: 'PROGRESS/CREATE_PROGRESS',
  UPDATE_PROGRESS: 'PROGRESS/UPDATE_PROGRESS',
  DELETE_PROGRESS: 'PROGRESS/DELETE_PROGRESS',
};
